### ISSUE TITLE
Shorter citation count format

### ISSUE THREAD

**Issue by jakemkc** [TobiHol/zotero-mas-metadata#1]
Hi,

I just tried to use the MAS plugin to replace Google Scholar plugin to handle citation count in my Zotero library.

It works great and thank you for the effort to develop the plugin for the Zotero community. 

However, is it possible to shorten the information in the Extra column?

For example, a record in the Extra column can be "ECC: 0000025". I need to make the column width large enough to see it has 25 citations, and it takes up space.

Could that be something as "00025", or even better, an option for us to set how many digits to show?

Best,
Jake

**Comment by tobihol** [comment]
Hi Jake,


thanks for the feedback! The reason for the zeros is that all the citation entries have to have the same amount of digits to be sortable. If you use a lower amount of digits, entries with high citation counts can't be represented anymore.

There are two ways to fix this problem:
(1) Add an option to change the amount of digits or just automatically have the amount of digits be equivalent to the digits needed to represent the highest cited entry in your library. E.g. your highest cited entry has 122 citations therefore the Extra column for your 25 citation papers would look like this "ECC: 025". (or maybe "025 ECC" so you would need even less space)
(2) Add a column to represent the citation count and don't put it in the Extra column. There would be no need for the leading zeros anymore.

Implementing (1) should be pretty easy, and I should get around to it next week. I think (2) takes a little bit more time, but I want to eventually do that to also add other columns with more metadata information. 


Best,
Tobi

**Comment by tobihol** [comment]
I implemented (1) in b3e31c7e9ad21c0f5a90f3d45b1ce2ca27b416a6 and made a new release with it. Let me know if it works for you!

**Comment by jakemkc** [comment]
Just tried, it works perfectly, thanks!

Jake
